dcConsData = [
	{name:"Icon_Emoji_001_Paimon_No_problem21.png", keywords:["페이몬1"], tags:["원신"]},
	{name:"Icon_Emoji_002_Paimon_Ship_out!.png", keywords:["페이몬2"], tags:["원신"]},
	{name:"Icon_Emoji_003_Paimon_Hehe7E.png", keywords:["페이몬3"], tags:["원신"]},
	{name:"Icon_Emoji_005_Paimon_Surprised21.png", keywords:["페이몬4"], tags:["원신"]},
	{name:"Icon_Emoji_006_Paimon_Too_easy21.png", keywords:["페이몬5"], tags:["원신"]},
	{name:"Icon_Emoji_053_Ganyu_Snoozing.png", keywords:["감우1"], tags:["원신"]},
	{name:"Icon_Emoji_054_Ganyu_No_touching21.png", keywords:["감우2"], tags:["원신"]},
	{name:"Icon_Emoji_055_Ganyu_Upset.png", keywords:["감우3"], tags:["원신"]},
	{name:"Icon_Emoji_056_Ganyu_Not_bad.png", keywords:["감우4"], tags:["원신"]},
	{name:"Icon_Emoji_057_Ganyu_Pray.png", keywords:["감우5"], tags:["원신"]},
	{name:"Icon_Emoji_058_Ganyu_Good_Morning.png", keywords:["감우6"], tags:["원신"]},
	{name:"Icon_Emoji_033_Zhongli_Sipping_tea.png", keywords:["종려1"], tags:["원신"]},
	{name:"Icon_Emoji_034_Zhongli_I27ll_take_them_all.png", keywords:["종려2"], tags:["원신"]},
	{name:"Icon_Emoji_035_Zhongli_Thinking.png", keywords:["종려3"], tags:["원신"]},
	{name:"Icon_Emoji_036_Zhongli_Spread_hands.png", keywords:["종려4"], tags:["원신"]},
	{name:"Icon_Emoji_085_Yanfei_No_problem.png", keywords:["연비1"], tags:["원신"]},
	{name:"Icon_Emoji_086_Yanfei_I_can27t_sleep.png", keywords:["연비2"], tags:["원신"]},
	{name:"Icon_Emoji_087_Yanfei_What_to_do....png", keywords:["연비3"], tags:["원신"]},
	{name:"Icon_Emoji_088_Yanfei_Pleased.png", keywords:["연비4"], tags:["원신"]},
	{name:"Icon_Emoji_014_Lumine_Please7E.png", keywords:["여행자1"], tags:["원신"]},
	{name:"Icon_Emoji_016_Lumine_Will_1_Mora_do3F.png", keywords:["여행자2"], tags:["원신"]},
	{name:"Icon_Emoji_013_Aether_Fall_asleep.png", keywords:["남행자1"], tags:["원신"]},
	{name:"Icon_Emoji_015_Aether_Alert.png", keywords:["남행자2"], tags:["원신"]},
	{name:"Icon_Emoji_021_Mona_Love.png", keywords:["모나1"], tags:["원신"]},
	{name:"Icon_Emoji_022_Mona_Hehe.png", keywords:["모나2"], tags:["원신"]},
	{name:"Icon_Emoji_047_Mona_So_hungry....png", keywords:["모나3"], tags:["원신"]},
	{name:"Icon_Emoji_048_Mona_Mora21.png", keywords:["모나4"], tags:["원신"]},
	{name:"Icon_Emoji_023_Keqing_Like.png", keywords:["각청1"], tags:["원신"]},
	{name:"Icon_Emoji_024_Keqing_Good_Night.png", keywords:["각청2"], tags:["원신"]},
	{name:"Icon_Emoji_045_Keqing_Mad.png", keywords:["각청3"], tags:["원신"]},
	{name:"Icon_Emoji_046_Keqing_I_refuse..png", keywords:["각청4"], tags:["원신"]},
	{name:"Icon_Emoji_065_Hu_Tao_Evil_laugh.png", keywords:["호두1"], tags:["원신"]},
	{name:"Icon_Emoji_066_Hu_Tao_Reciting_poetry.png", keywords:["호두2"], tags:["원신"]},
	{name:"Icon_Emoji_067_Hu_Tao_Messed_up.png", keywords:["호두3"], tags:["원신"]},
	{name:"Icon_Emoji_068_Hu_Tao_Adorable.png", keywords:["호두4"], tags:["원신"]},
	{name:"Icon_Emoji_069_Hu_Tao_Frighten.png", keywords:["호두5"], tags:["원신"]},
	{name:"Icon_Emoji_070_Hu_Tao_I27ve_got_this21.png", keywords:["호두6"], tags:["원신"]},
	{name:"Icon_Emoji_071_Hu_Tao_Yawn.png", keywords:["호두7"], tags:["원신"]},
	{name:"Icon_Emoji_072_Hu_Tao_Pardon_me.png", keywords:["호두8"], tags:["원신"]},
	{name:"Icon_Emoji_017_Sucrose_OK.png", keywords:["설탕1"], tags:["원신"]},
	{name:"Icon_Emoji_018_Sucrose_I27ll_be_good.png", keywords:["설탕2"], tags:["원신"]},
	{name:"Icon_Emoji_019_Sucrose_Doubt.png", keywords:["설탕3"], tags:["원신"]},
	{name:"Icon_Emoji_020_Sucrose_Shame.png", keywords:["설탕4"], tags:["원신"]},
	{name:"Icon_Emoji_059_Sucrose_You_can_do_it21.png", keywords:["설탕5"], tags:["원신"]},
	{name:"Icon_Emoji_060_Sucrose_Recording.png", keywords:["설탕6"], tags:["원신"]},
	{name:"Icon_Emoji_025_Qiqi_Fallen.png", keywords:["치치1"], tags:["원신"]},
	{name:"Icon_Emoji_026_Qiqi_Secretly_observing.png", keywords:["치치2"], tags:["원신"]},
	{name:"Icon_Emoji_027_Qiqi_Oh21.png", keywords:["치치3"], tags:["원신"]},
	{name:"Icon_Emoji_028_Venti_Expectant.png", keywords:["벤티1"], tags:["원신"]},
	{name:"Icon_Emoji_029_Venti_Shocked.png", keywords:["벤티2"], tags:["원신"]},
	{name:"Icon_Emoji_030_Venti_I_have_an_idea21.png", keywords:["벤티3"], tags:["원신"]},
	{name:"Icon_Emoji_031_Venti_Falling_petals.png", keywords:["벤티4"], tags:["원신"]},
	{name:"Icon_Emoji_032_Venti_Applause.png", keywords:["벤티5"], tags:["원신"]},
	{name:"Icon_Emoji_063_Fischl_Not_at_all21.png", keywords:["피슬1"], tags:["원신"]},
	{name:"Icon_Emoji_064_Fischl_Hahaha.png", keywords:["피슬2"], tags:["원신"]},
	{name:"Icon_Emoji_007_Amber_Noooo21.png", keywords:["앰버1"], tags:["원신"]},
	{name:"Icon_Emoji_010_Amber_Save_me21.png", keywords:["앰버2"], tags:["원신"]},
	{name:"Icon_Emoji_012_Amber_Outta_my_way21.png", keywords:["앰버3"], tags:["원신"]},
	{name:"Icon_Emoji_008_Jean_Oh....png", keywords:["진1"], tags:["원신"]},
	{name:"Icon_Emoji_009_Lisa_Well_done!.png", keywords:["리사1"], tags:["원신"]},
	{name:"Icon_Emoji_011_Kaeya_That27s_funny21.png", keywords:["케이야1"], tags:["원신"]},
	{name:"Icon_Emoji_037_Tartaglia_Sigh.png", keywords:["타르탈리아1"], tags:["원신"]},
	{name:"Icon_Emoji_038_Tartaglia_Pleased.png", keywords:["타르탈리아2"], tags:["원신"]},
	{name:"Icon_Emoji_061_Tartaglia_Shocked.png", keywords:["타르탈리아3"], tags:["원신"]},
	{name:"Icon_Emoji_062_Tartaglia_The_light_fades.png", keywords:["타르탈리아4"], tags:["원신"]},
	{name:"Icon_Emoji_039_Diona_Irritable.png", keywords:["디오나1"], tags:["원신"]},
	{name:"Icon_Emoji_040_Diona_Bored.png", keywords:["디오나2"], tags:["원신"]},
	{name:"Icon_Emoji_041_Diona_Fearsome.png", keywords:["디오나3"], tags:["원신"]},
	{name:"Icon_Emoji_042_Diona_Proud.png", keywords:["디오나4"], tags:["원신"]},
	{name:"Icon_Emoji_043_Xinyan_I27m_heating_up21.png", keywords:["신염1"], tags:["원신"]},
	{name:"Icon_Emoji_044_Xinyan_So_annoying21.png", keywords:["신염2"], tags:["원신"]},
	{name:"Icon_Emoji_049_Albedo_Have_some_flowers.png", keywords:["알베도1"], tags:["원신"]},
	{name:"Icon_Emoji_050_Albedo_It_was_nothing.png", keywords:["알베도2"], tags:["원신"]},
	{name:"Icon_Emoji_051_Albedo_What_happened3F.png", keywords:["알베도3"], tags:["원신"]},
	{name:"Icon_Emoji_052_Albedo_Cold.png", keywords:["알베도4"], tags:["원신"]},
	{name:"Icon_Emoji_073_Xiao_Eating.png", keywords:["소1"], tags:["원신"]},
	{name:"Icon_Emoji_074_Xiao_Rubs_eyes.png", keywords:["소2"], tags:["원신"]},
	{name:"Icon_Emoji_075_Xiao_Have_a_seat.png", keywords:["소3"], tags:["원신"]},
	{name:"Icon_Emoji_076_Xiao_Bring_it21.png", keywords:["소4"], tags:["원신"]},
	{name:"Icon_Emoji_077_Xiao_Doubt.png", keywords:["소5"], tags:["원신"]},
	{name:"Icon_Emoji_078_Xiao_Dazed.png", keywords:["소6"], tags:["원신"]},
	{name:"Icon_Emoji_079_Xiao_Indifferent.png", keywords:["소7"], tags:["원신"]},
	{name:"Icon_Emoji_080_Xiao_Frown.png", keywords:["소8"], tags:["원신"]},
	{name:"Icon_Emoji_081_Eula_Praise.png", keywords:["유라1"], tags:["원신"]},
	{name:"Icon_Emoji_082_Eula_Let_me_see.png", keywords:["유라2"], tags:["원신"]},
	{name:"Icon_Emoji_083_Eula_Cheers21.png", keywords:["유라4"], tags:["원신"]},
	{name:"Icon_Emoji_084_Eula_Time_to_eat21.png", keywords:["유라5"], tags:["원신"]},
	{name:"Icon_Emoji_089_Azhdaha_Perplexed.png", keywords:["야타1"], tags:["원신"]},
	{name:"Icon_Emoji_090_Azhdaha_Rawr.png", keywords:["야타2"], tags:["원신"]},
	{name:"Icon_Emoji_091_Azhdaha_Confused.png", keywords:["야타3"], tags:["원신"]},
	{name:"Icon_Emoji_092_Azhdaha_Resting.png", keywords:["야타4"], tags:["원신"]},
	{name:"Icon_Emoji_093_Rosaria_Dislike.png", keywords:["로자리아1"], tags:["원신"]},
	{name:"Icon_Emoji_094_Rosaria_Sweating.png", keywords:["로자리아2"], tags:["원신"]},
	{name:"Icon_Emoji_095_Rosaria_Stare.png", keywords:["로자리아3"], tags:["원신"]},
	{name:"Icon_Emoji_096_Rosaria_Clocking_out.png", keywords:["로자리아4"], tags:["원신"]},	
	{name:"1st (37).gif", keywords:["유리카1"], tags:["1번가"]},
	{name:"1st (38).gif", keywords:["유리카2"], tags:["1번가"]},
	{name:"1st (39).gif", keywords:["유리카3"], tags:["1번가"]},
	{name:"1st (40).gif", keywords:["유리카4"], tags:["1번가"]},
	{name:"1st (41).gif", keywords:["유리카5"], tags:["1번가"]},
	{name:"1st (42).gif", keywords:["유리카6"], tags:["1번가"]},	
	{name:"1st (43).gif", keywords:["아테나1"], tags:["1번가"]},
	{name:"1st (44).gif", keywords:["아테나2"], tags:["1번가"]},
	{name:"1st (45).gif", keywords:["아테나3"], tags:["1번가"]},
	{name:"1st (46).gif", keywords:["아테나4"], tags:["1번가"]},
	{name:"1st (47).gif", keywords:["아테나5"], tags:["1번가"]},
	{name:"1st (48).gif", keywords:["아테나6"], tags:["1번가"]},	
	{name:"1st (1).gif", keywords:["세이비1"], tags:["1번가"]},
	{name:"1st (2).gif", keywords:["세이비2"], tags:["1번가"]},
	{name:"1st (3).gif", keywords:["세이비3"], tags:["1번가"]},
	{name:"1st (4).gif", keywords:["세이비4"], tags:["1번가"]},
	{name:"1st (5).gif", keywords:["세이비5"], tags:["1번가"]},
	{name:"1st (6).gif", keywords:["세이비6"], tags:["1번가"]},
	{name:"1st (7).gif", keywords:["칸나1"], tags:["1번가"]},
	{name:"1st (8).gif", keywords:["칸나2"], tags:["1번가"]},
	{name:"1st (9).gif", keywords:["칸나3"], tags:["1번가"]},
	{name:"1st (10).gif", keywords:["칸나4"], tags:["1번가"]},
	{name:"1st (11).gif", keywords:["칸나5"], tags:["1번가"]},
	{name:"1st (12).gif", keywords:["칸나6"], tags:["1번가"]},	
	{name:"1st (13).gif", keywords:["나기1"], tags:["1번가"]},
	{name:"1st (14).gif", keywords:["나기2"], tags:["1번가"]},
	{name:"1st (15).gif", keywords:["나기3"], tags:["1번가"]},
	{name:"1st (16).gif", keywords:["나기4"], tags:["1번가"]},
	{name:"1st (17).gif", keywords:["나기5"], tags:["1번가"]},
	{name:"1st (18).gif", keywords:["나기6"], tags:["1번가"]},
	{name:"1st (19).gif", keywords:["사에코1"], tags:["1번가"]},
	{name:"1st (20).gif", keywords:["사에코2"], tags:["1번가"]},
	{name:"1st (21).gif", keywords:["사에코3"], tags:["1번가"]},
	{name:"1st (22).gif", keywords:["사에코4"], tags:["1번가"]},
	{name:"1st (23).gif", keywords:["사에코5"], tags:["1번가"]},
	{name:"1st (24).gif", keywords:["사에코6"], tags:["1번가"]},		
	{name:"1st (25).gif", keywords:["시오츠키1"], tags:["1번가"]},
	{name:"1st (26).gif", keywords:["시오츠키2"], tags:["1번가"]},
	{name:"1st (27).gif", keywords:["시오츠키3"], tags:["1번가"]},
	{name:"1st (28).gif", keywords:["시오츠키4"], tags:["1번가"]},
	{name:"1st (29).gif", keywords:["시오츠키5"], tags:["1번가"]},
	{name:"1st (30).gif", keywords:["시오츠키6"], tags:["1번가"]},	
	{name:"1st (31).gif", keywords:["렌신1"], tags:["1번가"]},
	{name:"1st (32).gif", keywords:["렌신2"], tags:["1번가"]},
	{name:"1st (33).gif", keywords:["렌신3"], tags:["1번가"]},
	{name:"1st (34).gif", keywords:["렌신4"], tags:["1번가"]},
	{name:"1st (35).gif", keywords:["렌신5"], tags:["1번가"]},
	{name:"1st (36).gif", keywords:["렌신6"], tags:["1번가"]},
	{name:"1st (49).gif", keywords:["켄이치1"], tags:["1번가"]},
	{name:"1st (50).gif", keywords:["켄이치2"], tags:["1번가"]},
	{name:"1st (51).gif", keywords:["켄이치3"], tags:["1번가"]},
	{name:"1st (52).gif", keywords:["켄이치4"], tags:["1번가"]},
	{name:"1st (53).gif", keywords:["켄이치5"], tags:["1번가"]},
	{name:"1st (54).gif", keywords:["켄이치6"], tags:["1번가"]},
	{name:"1st (55).gif", keywords:["쟝마루1"], tags:["1번가"]},
	{name:"1st (56).gif", keywords:["쟝마루2"], tags:["1번가"]},
	{name:"1st (57).gif", keywords:["쟝마루3"], tags:["1번가"]},
	{name:"1st (58).gif", keywords:["쟝마루4"], tags:["1번가"]},
	{name:"1st (59).gif", keywords:["쟝마루5"], tags:["1번가"]},
	{name:"1st (60).gif", keywords:["쟝마루6"], tags:["1번가"]},	
	{name:"Mahjong (15).png", keywords:["푸흡"], tags:["작혼"]},
	{name:"Mahjong (16).png", keywords:["찌릿"], tags:["작혼"]},
	{name:"Mahjong (17).png", keywords:["귀여우셔라"], tags:["작혼"]},
	{name:"Mahjong (18).png", keywords:["폐인"], tags:["작혼"]},
	{name:"Mahjong (19).png", keywords:["소란소란"], tags:["작혼"]},
	{name:"Mahjong (20).png", keywords:["꽃미남"], tags:["작혼"]},
	{name:"Mahjong (21).png", keywords:["헤이"], tags:["작혼"]},
	{name:"Mahjong (22).png", keywords:["받아치기"], tags:["작혼"]},
	{name:"Mahjong_1.gif", keywords:["짱냥이1"], tags:["작혼"]},
	{name:"Mahjong_2.gif", keywords:["짱냥이2"], tags:["작혼"]},
	{name:"Mahjong_3.gif", keywords:["짱냥이3"], tags:["작혼"]},
	{name:"Mahjong_4.gif", keywords:["짱냥이4"], tags:["작혼"]},
	{name:"Mahjong_5.gif", keywords:["짱냥이5"], tags:["작혼"]},
	{name:"Mahjong_6.gif", keywords:["짱냥이6"], tags:["작혼"]},
	{name:"Mahjong_7.gif", keywords:["짱냥이7"], tags:["작혼"]},
	{name:"Mahjong (1).png", keywords:["용의자"], tags:["작혼"]},
	{name:"Mahjong (2).png", keywords:["미안"], tags:["작혼"]},
	{name:"Mahjong (3).png", keywords:["풉"], tags:["작혼"]},
	{name:"Mahjong (4).png", keywords:["쯔모"], tags:["작혼"]},
	{name:"Mahjong (5).png", keywords:["승부결정"], tags:["작혼"]},
	{name:"Mahjong (6).png", keywords:["아카기"], tags:["작혼"]},
	{name:"Mahjong (7).png", keywords:["야바"], tags:["작혼"]},
	{name:"Mahjong (8).png", keywords:["와시즈"], tags:["작혼"]},
	{name:"Mahjong (9).png", keywords:["불안하다냐"], tags:["작혼"]},
	{name:"Mahjong (10).png", keywords:["최고다냥"], tags:["작혼"]},
	{name:"Mahjong (11).png", keywords:["따봉"], tags:["작혼"]},
	{name:"Mahjong (12).png", keywords:["깡"], tags:["작혼"]},
	{name:"Mahjong (13).png", keywords:["다어데갔노"], tags:["작혼"]},
	{name:"Mahjong (14).png", keywords:["히비키"], tags:["작혼"]},	
	{name:"blue_01.gif", keywords:["몰루", "몰?루"], tags:["블루아카이브"]},
	{name:"blue_02.gif", keywords:["뿅"], tags:["블루아카이브"]},
	{name:"blue_03.gif", keywords:["안녕하세요"], tags:["블루아카이브"]},
	{name:"blue_04.gif", keywords:["네"], tags:["블루아카이브"]},
	{name:"blue_05.gif", keywords:["아냐"], tags:["블루아카이브"]},
	{name:"blue_06.gif", keywords:["울먹"], tags:["블루아카이브"]},
	{name:"blue_07.gif", keywords:["행복합니다", "행복"], tags:["블루아카이브"]},
	{name:"blue_08.gif", keywords:["선넘네"], tags:["블루아카이브"]},
	{name:"blue_09.gif", keywords:["가자"], tags:["블루아카이브"]},
	{name:"blue_10.gif", keywords:["선생님", "선생님?"], tags:["블루아카이브"]},
	{name:"blue_11.gif", keywords:["불태웠어", "재"], tags:["블루아카이브"]},
	{name:"blue_12.gif", keywords:["ㅋㅋㅋ"], tags:["블루아카이브"]},
	{name:"blue_13.gif", keywords:["ㅠㅠ"], tags:["블루아카이브"]},
	{name:"blue_14.gif", keywords:["?!!", "?!"], tags:["블루아카이브"]},
	{name:"blue_15.gif", keywords:["잘자"], tags:["블루아카이브"]},
	{name:"blue_16.gif", keywords:["귀찮아"], tags:["블루아카이브"]},
	{name:"blue_17.gif", keywords:["아루", "아!루"], tags:["블루아카이브"]},
	{name:"blue_18.gif", keywords:["반짝", "반짝반짝"], tags:["블루아카이브"]},
	{name:"blue_19.gif", keywords:["줘"], tags:["블루아카이브"]},
	{name:"blue_20.gif", keywords:["더줘"], tags:["블루아카이브"]},
	{name:"blue_21.gif", keywords:["갓겜입니다", "갓겜"], tags:["블루아카이브"]},
	{name:"blue_22.gif", keywords:["그래"], tags:["블루아카이브"]},
	{name:"blue_23.gif", keywords:["안돼"], tags:["블루아카이브"]},
	{name:"blue_24.gif", keywords:["고마워"], tags:["블루아카이브"]},
	{name:"blue_25.gif", keywords:["최고"], tags:["블루아카이브"]},
	{name:"blue_26.gif", keywords:["갸아아악"], tags:["블루아카이브"]},
	{name:"blue_27.gif", keywords:["저기"], tags:["블루아카이브"]},
	{name:"blue_28.gif", keywords:["흐에엥"], tags:["블루아카이브"]},
	{name:"blue_29.gif", keywords:["츄릅"], tags:["블루아카이브"]},	
	{name:"bl_01.gif", keywords:["흑작가"], tags:["흑작가"]},
	{name:"bl_02.gif", keywords:["화나"], tags:["흑작가"]},
	{name:"bl_03.png", keywords:["빼꼼"], tags:["흑작가"]},
	{name:"bl_04.gif", keywords:["파도루"], tags:["흑작가"]},
	{name:"icon_7.gif", keywords:["우리핵안녕"], tags:["우리핵"]},
	{name:"icon_13.gif", keywords:["우리핵박수"], tags:["우리핵"]},	
	{name:"icon_5.gif", keywords:["우리핵투정"], tags:["우리핵"]},
	{name:"icon_4.gif", keywords:["우리핵아닌데"], tags:["우리핵"]},	
	{name:"icon_8.gif", keywords:["우리핵쌍안경"], tags:["우리핵"]},
	{name:"icon_9.gif", keywords:["우리핵드럼"], tags:["우리핵"]},
	{name:"icon_14.gif", keywords:["우리핵빵야"], tags:["우리핵"]}	
	
];
