dcConsData = [
	{name:"Mahjong (15).png", keywords:["푸흡"], tags:["작혼"]},
	{name:"Mahjong (16).png", keywords:["찌릿"], tags:["작혼"]},
	{name:"Mahjong (17).png", keywords:["귀여우셔라"], tags:["작혼"]},
	{name:"Mahjong (18).png", keywords:["폐인"], tags:["작혼"]},
	{name:"Mahjong (19).png", keywords:["소란소란"], tags:["작혼"]},
	{name:"Mahjong (20).png", keywords:["꽃미남"], tags:["작혼"]},
	{name:"Mahjong (21).png", keywords:["헤이"], tags:["작혼"]},
	{name:"Mahjong (22).png", keywords:["받아치기"], tags:["작혼"]},
	{name:"Mahjong_1.gif", keywords:["짱냥이1"], tags:["작혼"]},
	{name:"Mahjong_2.gif", keywords:["짱냥이2"], tags:["작혼"]},
	{name:"Mahjong_3.gif", keywords:["짱냥이3"], tags:["작혼"]},
	{name:"Mahjong_4.gif", keywords:["짱냥이4"], tags:["작혼"]},
	{name:"Mahjong_5.gif", keywords:["짱냥이5"], tags:["작혼"]},
	{name:"Mahjong_6.gif", keywords:["짱냥이6"], tags:["작혼"]},
	{name:"Mahjong_7.gif", keywords:["짱냥이7"], tags:["작혼"]},
	{name:"Mahjong (1).png", keywords:["용의자"], tags:["작혼"]},
	{name:"Mahjong (2).png", keywords:["미안"], tags:["작혼"]},
	{name:"Mahjong (3).png", keywords:["풉"], tags:["작혼"]},
	{name:"Mahjong (4).png", keywords:["쯔모"], tags:["작혼"]},
	{name:"Mahjong (5).png", keywords:["승부결정"], tags:["작혼"]},
	{name:"Mahjong (6).png", keywords:["아카기"], tags:["작혼"]},
	{name:"Mahjong (7).png", keywords:["야바"], tags:["작혼"]},
	{name:"Mahjong (8).png", keywords:["와시즈"], tags:["작혼"]},
	{name:"Mahjong (9).png", keywords:["불안하다냐"], tags:["작혼"]},
	{name:"Mahjong (10).png", keywords:["최고다냥"], tags:["작혼"]},
	{name:"Mahjong (11).png", keywords:["따봉"], tags:["작혼"]},
	{name:"Mahjong (12).png", keywords:["깡"], tags:["작혼"]},
	{name:"Mahjong (13).png", keywords:["다어데갔노"], tags:["작혼"]},
	{name:"Mahjong (14).png", keywords:["히비키"], tags:["작혼"]},	
	{name:"blue_01.gif", keywords:["몰루", "몰?루"], tags:["블루아카이브"]},
	{name:"blue_02.gif", keywords:["뿅"], tags:["블루아카이브"]},
	{name:"blue_03.gif", keywords:["안녕하세요"], tags:["블루아카이브"]},
	{name:"blue_04.gif", keywords:["네"], tags:["블루아카이브"]},
	{name:"blue_05.gif", keywords:["아냐"], tags:["블루아카이브"]},
	{name:"blue_06.gif", keywords:["울먹"], tags:["블루아카이브"]},
	{name:"blue_07.gif", keywords:["행복합니다", "행복"], tags:["블루아카이브"]},
	{name:"blue_08.gif", keywords:["선넘네"], tags:["블루아카이브"]},
	{name:"blue_09.gif", keywords:["가자"], tags:["블루아카이브"]},
	{name:"blue_10.gif", keywords:["선생님", "선생님?"], tags:["블루아카이브"]},
	{name:"blue_11.gif", keywords:["불태웠어", "재"], tags:["블루아카이브"]},
	{name:"blue_12.gif", keywords:["ㅋㅋㅋ"], tags:["블루아카이브"]},
	{name:"blue_13.gif", keywords:["ㅠㅠ"], tags:["블루아카이브"]},
	{name:"blue_14.gif", keywords:["?!!", "?!"], tags:["블루아카이브"]},
	{name:"blue_15.gif", keywords:["잘자"], tags:["블루아카이브"]},
	{name:"blue_16.gif", keywords:["귀찮아"], tags:["블루아카이브"]},
	{name:"blue_17.gif", keywords:["아루", "아!루"], tags:["블루아카이브"]},
	{name:"blue_18.gif", keywords:["반짝", "반짝반짝"], tags:["블루아카이브"]},
	{name:"blue_19.gif", keywords:["줘"], tags:["블루아카이브"]},
	{name:"blue_20.gif", keywords:["더줘"], tags:["블루아카이브"]},
	{name:"blue_21.gif", keywords:["갓겜입니다", "갓겜"], tags:["블루아카이브"]},
	{name:"blue_22.gif", keywords:["그래"], tags:["블루아카이브"]},
	{name:"blue_23.gif", keywords:["안돼"], tags:["블루아카이브"]},
	{name:"blue_24.gif", keywords:["고마워"], tags:["블루아카이브"]},
	{name:"blue_25.gif", keywords:["최고"], tags:["블루아카이브"]},
	{name:"blue_26.gif", keywords:["갸아아악"], tags:["블루아카이브"]},
	{name:"blue_27.gif", keywords:["저기"], tags:["블루아카이브"]},
	{name:"blue_28.gif", keywords:["흐에엥"], tags:["블루아카이브"]},
	{name:"blue_29.gif", keywords:["츄릅"], tags:["블루아카이브"]},	
	{name:"bl_01.gif", keywords:["흑작가"], tags:["흑작가"]},
	{name:"bl_02.gif", keywords:["화나"], tags:["흑작가"]},
	{name:"bl_03.png", keywords:["빼꼼"], tags:["흑작가"]},
	{name:"bl_04.gif", keywords:["파도루"], tags:["흑작가"]},
	{name:"icon_7.gif", keywords:["우리핵안녕"], tags:["우리핵"]},
	{name:"icon_13.gif", keywords:["우리핵박수"], tags:["우리핵"]},	
	{name:"icon_5.gif", keywords:["우리핵투정"], tags:["우리핵"]},
	{name:"icon_4.gif", keywords:["우리핵아닌데"], tags:["우리핵"]},	
	{name:"icon_8.gif", keywords:["우리핵쌍안경"], tags:["우리핵"]},
	{name:"icon_9.gif", keywords:["우리핵드럼"], tags:["우리핵"]},
	{name:"icon_14.gif", keywords:["우리핵빵야"], tags:["우리핵"]}	
	
];
